# This project munges HTML, so slashes are not always the best delimiter
Style/RegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

# I have opinions on this subject.
Layout/SpaceInsideParens:
  EnforcedStyle: space
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Metrics/MethodLength:
  Max: 12
Style/FrozenStringLiteralComment:
  Enabled: false
